### ISSUE TITLE
get method returning original reference

### ISSUE THREAD

**Issue by wikiwong** [jpodwys/cache-service-cache-module#6]
Hello, thank you for providing this nifty tool!  I'm using superagent-cache, and noticed that the `get` method of this module is passing a reference of its cached value to the callback: https://github.com/jpodwys/cache-service-cache-module/blob/master/cacheModule.js#L53

I _was_ mutating this object, which ended up mutating the reference stored in this module.  I probably shouldn't have been mutating the return value to begin with (and have updated my code since) but out of curiosity, is there any reason not to return a new reference?  I think you're doing that in the `mget` method:  https://github.com/jpodwys/cache-service-cache-module/blob/master/cacheModule.js#L73

**Comment by jpodwys** [comment]
Thank you for the info, glad you're enjoying the repos! I've just created the [`clone-objects`](https://github.com/jpodwys/cache-service-cache-module/tree/clone-objects) branch with [these differences](https://github.com/jpodwys/cache-service-cache-module/compare/clone-objects?expand=1).

The `cloneObject` function I added is the same function I use in `superagent-cache` so I know it works well, but I don't know and haven't put the thought into whether this would break people who need clones of deeply-nested objects. Any input would be helpful--sorry, I'm rather distracted with holiday vacation.

Please test it out and let me know if the changes address your concern.

**Comment by wikiwong** [comment]
Hey @jpodwys , thanks so much for your attention to this.  I think this works for objects that are flat, but in order to truly return a new reference of the object, a deep clone is required.  In my case, I'm working with data that is two levels deep, and JavaScript is hanging on to the reference of this nested object even though you're cloning the top level keys.

Without bringing in a third party library, or using ES6 object spread syntax, it seems there isn't really an elegant way to accomplish this: http://stackoverflow.com/questions/4459928/how-to-deep-clone-in-javascript

I toggle back and forth between whether or not it's the responsibility of the library, or the integration to ensure that the original reference isn't being changed.  I have it working correctly in my app by creating a new reference to operate on, but if you think the library should perform the deep cloning and return the new reference, I'm happy to help us get there.  Let me know what you think.

**Comment by jpodwys** [comment]
Thanks for your feedback!

I've used this elsewhere in the past and think it may be sufficient:

`var cloned = JSON.parse(JSON.stringify(objectToClone));`

According to the link you pasted, though, this could represent a breaking change if anyone is storing functions in their objects. 

That being said, this behavior would be consistent with `cache-service-redis` because that module stringifies before saving to redis and parses when retrieving. In the interest of sibling modules that behave as similarly as possible and code simplicity, I'm leaning towards doing it this way. 

As for your question about whether this is the module's responsibility, I think it is. `cache-service-redis` already returns a reference and so does this lib's `mget` as you've pointed out. I think you should be free to mutate the response as you see fit. 

Any thoughts?

**Comment by wikiwong** [comment]
@jpodwys Aligning with the `cache-service-redis` module is a good argument for cloning the object before returning it.  You make a good point that functions won't get cached properly, but I think the majority of uses for this module are for interacting with APIs that most likely don't return function definitions in their responses.  I'm assuming a little bit here, but it sounds like a potentially breaking change with a low probability of regression.

Thanks again for taking a look at this!!

**Comment by jpodwys** [comment]
@wikiwong It's a good point that it's a potentially breaking change. I'm hesitant to bump the major version here because I had hoped to keep all of my cache modules in major release sync, but perhaps it's necessary. I'll have to think on it. I suppose I can introduce an optional flag that's default disabled that, when enabled, clones the returned data. That feels weird too, though haha.

**Comment by wikiwong** [comment]
@jpodwys Yeah it's a tough call.  If we knew it was only being used for API responses, we could assume that nobody is using it to cache functions, but I'm not sure what the extent of its usage is.  I suppose we could write our own recursive deep cloning function, or lean one already created, but that increases the risk of regression, and would likely require maintenance as JavaScript evolves and potentially acquires new types.  🤔

**Comment by jpodwys** [comment]
This has gained some more attention. I'm ready to work it out, but we need to answer the following questions:

1. Do we need to pull in a true deep clone implementation, or is `JSON.parse(JSON.stringify(objectToClone));` sufficient? As a refresher, the `JSON.parse` implementation, while short and fast, will not handle function calls or date objects correctly.
2. How important is it to maintain behavioral similarity to `cache-service-redis`? I've stated in documentation that the two modules are interchangeable as far as APIs go. Since `cache-service-redis` uses the `JSON.stringify` method, should I go that route to help ensure they are truly interchangeable?
3. Is this a breaking change? If it's not, we can bake it directly in. If it is, we need to include it as a config or cut a breaking release.

If we're ok with the limitations it introduces, `JSON.parse(JSON.stringify(objectToClone));` is simple and fast. If we need a more robust solution that is still pretty short and has fewer limitations, [this stack overflow answer](http://stackoverflow.com/questions/728360/how-do-i-correctly-clone-a-javascript-object#answer-728694) has a good implementation.

**Comment by jpodwys** [comment]
@wikiwong not sure you still use this lib, but I just published `2.0.0` to npm. The release addresses the issue. I also released `superagent-cache#3.0.0` which consumes `cache-service-cache-module#2.0.0`.
